[build]
  publish = "."
  command = "cp static-index.html index.html"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  PHP_VERSION = "8.0"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
